<?php
return array(
    'dictScrollTitleValue'=>'Scroll to the top of the page',
    'dictSiteDescription'=>'Building a frontend / backend setup for a simple, multi-language website using Bootstrap 4 with the Fat-Free PHP framework.',
    'dictMenuToggle'=>'Menu toggle',
    'dictToggle'=>'toggle',
    'dictNavDetails'=>'Details',
    'dictNavLanguage'=>'Language',
    'dictNoticeIE'=>'Our site does not support versions of Internet Explorer older than IE9. We apologize for the inconvenience.',
    'dictNoticeEUcookie1'=>'Cookie Notice (for EU compliance)',
    'dictNoticeEUcookie2'=>'We use Google analytics to understand how people find and use our site. To enable us to anonymously collect information on how our site is being used, please click or press the Accept button. That authorizes us to: place a cookie on your device to remember your choice; to instruct your browser to send information (including your IP address) to Google; and for Google to place cookies related to our site on your browser.',
    'dictNoticeEUcookie3'=>'To decline the use of cookies and Google services, click or press the Opt-out button.',
    'dictNoticeEUcookie4a'=>'For more information on our use of cookies, please review our ',
    'dictNoticeEUcookie4b'=>'Site Terms of Use / Privacy Policy',
    'dictNoticeEUcookie4c'=>'Privacy policy',
    'dictNoticeEUcookie4d'=>'.',
    'dictNoticeEUcookie5a'=>'Accept tracking cookies',
    'dictNoticeEUcookie5b'=>'Accept',
    'dictNoticeEUcookie6a'=>'Reject tracking cookies',
    'dictNoticeEUcookie6b'=>'Opt-out',
    'dictNoticeSkipLink'=>'Skip to main content',
    'dictLogoAltText' =>'Site Construction – Logo is a safety helmet – link to the home page',
    'dictFooterHeading1'=>'About this site',
    'dictFooterContent1'=>'This site is an experiment in creating a dynamic website. The files are available on <a href="https://github.com/RichDeBourke/simple-f3-multi-lang-site" title="GitHub repository with the Fat-Free Framework and Bootstrap 4 files">GitHub</a> and most of the logic for the site is documented within. A similar website built with Fat-Free & Bootstrap 5 is at <a href="https://sbf-bootstrap5.alwaysdata.net/">sbf-bootstrap5.alwaysdata.net/</a>.',
    'dictFooterHeading2'=>'About me',
    'dictFooterContent2'=>'I help Korean businesses with their English com&shy;mu&shy;ni&shy;cation (presen&shy;tations, web content, and emails) and web design.',
    'dictFooterHeading3'=>'Contact',
    'dictFooterContent3'=>'If you have questions about this site or if you need help with business in Korea, you can contact me at:
                        <script>
                            var name = "&#115;&#98;&#102;&#46;&#99;&#111;&#110;&#115;&#117;&#108;&#116;&#105;&#110;&#103;&#46;&#107;&#111;&#114;&#101;&#97;",
                                host = "&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;",
                                linktext,
                                subject = "?subject=Inquiry%20via%20Website";
                            linktext = name + "&#64;" + host + subject;
                            document.write(\'<a class="email" title="Email SBF Consulting" href="\' + \'mai\' + \'lto:\' + linktext + \'">\' + name + "&#64;" + host + \'</a>\');
                        </script>.',
    'dictFooterTerms'=>'Terms of Use | Privacy Policy',
    'dictFooterTermsTitle'=>'Terms of Use for this site including privacy',
    'dictFooterCopyrightTitle'=>'The website for my consulting business in Korea',
    'dict404PageTitle'=>'404 - Page not found error',
    'dict404PageDescription'=>'Page not found error',
    'dict404NotFoundHeader'=>'Page Not Found — A 404 Error',
    'dict404PageURL'=>'There is no page at: <strong>{0}</strong>',
    'dict404Notice1'=>'This may be because:',
    'dict404Notice2'=>'The page you are looking for is no longer available,',
    'dict404Notice3'=>'or you clicked a link from another site that has an error,',
    'dict404Notice4'=>'or the portion you typed, <strong>{0},</strong> has an error.',
    'dict404Notice5'=>'Please try the links above, or contact us for assistance.',
    'dict404Looked'=>'We looked, but we can&rsquo;t find the page you requested',
    'dict500PageTitle'=>'5XX - Server error',
    'dict500PageDescription'=>'There is a problem with our server',
    'dict500ServerErrorHeader'=>'We&rsquo;re tackling a {0} error',
    'dict500Notice1'=>'There&rsquo;s something wrong with our server (there&rsquo;s nothing wrong on your side).',
    'dict500Notice2'=>'As you can see, we&rsquo;re going through our code (<em>not really &ndash; it&rsquo;s just an animation, but hopefully we do know about the problem and we are working to resolve it</em>).',
    'dict500Notice3'=>'Here are a few things you can try that may resolve the problem:',
    'dict500Notice4'=>'<strong>Refresh the page</strong> (sometimes this helps)',
    'dict500Notice5'=>'<strong>Try again</strong> in 30 minutes',
    'dict500Notice6'=>'<strong>Email us</strong> and let us know what&rsquo;s happening',
    'dict500Notice7'=>'We apologize for the inconvenience.',
    'dictContactPageTitle'=>'Contact Us',
    'dictContactPageDescription'=>'You can contact us by via a contact form or by email',
    'dictContact01'=>'Contact us',
    'dictContact02'=>'Your name',
    'dictContact03'=>'Name',
    'dictContact04'=>'Your email',
    'dictContact05'=>'email@example.com',
    'dictContact06'=>'Your subject',
    'dictContact07'=>'Subject',
    'dictContact08'=>'Your message',
    'dictContact09'=>'Message',
    'dictContact10'=>'Thank you for wanting to contacting us, but as this host does not support email, the contact form does not work. Please use the email address in the footer.',
    'dictContact11'=>'We will respond to your request as quickly as we can.',
    'dictContact12'=>'Name is required',
    'dictContact13'=>'email is required',
    'dictContact14'=>'Invalid email format',
    'dictContact15'=>'Subject is required',
    'dictContact16'=>'Required',
    'dictContact17'=>'Only letters and white space allowed',
    'dictContact18'=>'Submit',
    'dictContact19'=>'Contact information',
    'dictTermsPageTitle'=>'Terms of Use | Privacy Policy',
    'dictTermsPageDescription'=>'Conditions for using this site and information about collecting personal information',
    'dictTermsOptOutQuestion'=>'Please confirm you do not want to use Google services.'
);
